### ISSUE TITLE
Cannot legally use

### ISSUE THREAD

**Issue by CoolCat467** [Beyley/fbz#1]
Without a license attached, I cannot legally use this program. ([website about legal side of open source](https://opensource.guide/legal/))
>When you make a creative work (such as writing, graphics, or code), that work is under exclusive copyright by default. In general, that means nobody else can use, copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation.

**Comment by Beyley** [comment]
i dont think its that serious, this is a funny minecraft program, but sure, i tossed it under GPLv2
